server:
  port: 80   # HTTP (Tomcat) port
#  servlet:
#    context-path: /adminconsole   # 配置项目名 47.107.128.84

# DataSource Config
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure  # 为了某些版本的springboot  @SpringBootApplication(exclude= {DataSourceAutoConfiguration.class}) 无法生效
  datasource:
    dynamic:
      primary: db1 # 配置默认数据库
      datasource:
        db1: # 数据源1配置
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://xijia.plus:3306/spring-boot-plus2?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
          username: root
          password: root123456
          type: com.alibaba.druid.pool.DruidDataSource
#        db2: # 数据源2配置
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://xijia.plus:3306/spring-boot-plus2?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
#          username: root
#          password: root123456
#          type: com.alibaba.druid.pool.DruidDataSource