## 生产环境

## HTTP (Tomcat) port
server:
  port: 9049


# DataSource Config spring.datasource.dynamic.datasource.db1.url
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure  # 为了某些版本的springboot  @SpringBootApplication(exclude= {DataSourceAutoConfiguration.class}) 无法生效
  datasource:
    dynamic:
      primary: db1 # 配置默认数据库
      datasource:
        db1: # 数据源1配置
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://xijia.plus/spring-boot-plus2?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
          username: root
          password: root123456
          type: com.alibaba.druid.pool.DruidDataSource


## 微信公众号 相关配置信息(此为个人测试号)
wx:
  mp:
    configs:
      - appId: wxa997b110821cbfd6                    # 第一个公众号的appid
        secret: a5cee82a40995afc5bc14d17058908c1     # 公众号的appsecret
        token: 123456789                             # 接口配置里的Token值
        aesKey: 123456789                            # 接口配置里的EncodingAESKey值


## 阿里云oss配置 (此阿里云为个人账号提供, 请自行切换为自己的阿里云oss地址，一旦发现滥用，将关闭此服务地址)
aliyun:
  oss:
    # oss访问地址  外网-> oss-cn-shenzhen.aliyuncs.com   内网-> oss-cn-shenzhen-internal.aliyuncs.com
    endpoint: oss-cn-shenzhen.aliyuncs.com
    # 阿里云下oss 的 accessKeyId和accessKeySecret(访问密钥，您可以在控制台上创建和查看)
    accessKeyId: LTAI4Fyfy2DTf4yUrvKqHwH4
    accessKeySecret: Jf3gn1kSRLdh1j14F5mznnJyIBIhA8
    # Bucket 名称
    bucketName: xijia-sz


## 路由转发, 目前主要用于阿里云oss 文件访问路由转发：外网: xijia-sz.oss-cn-shenzhen.aliyuncs.com   内网-> xijia-sz.oss-cn-shenzhen-internal.aliyuncs.com
zuul:
  routes:
    ali-oss:
      id: aliOss
      path: /oss/**
      stripPrefix: false
      url: http://xijia-sz.oss-cn-shenzhen.aliyuncs.com

## logback日志输出
logging:
  # 日志目录, 线上请配置linux 绝对路径 如：/usr/local/work/xijia2/logs
  filePath: /usr/local/work/xijia2/logs
  # 配置日志路径即可实时输出到 spring-boot-admin 日志管理
  file: /usr/local/work/xijia2/log.txt