# HTTP (Tomcat) port
server:
  port: 9049


## 阿里云oss配置
aliyun:
  oss:
    # 阿里云下oss 的 accessKeyId和accessKeySecret(访问密钥，您可以在控制台上创建和查看)
    accessKeyId: LTAI4Fyfy2DTf4yUrvKqHwH4
    accessKeySecret: Jf3gn1kSRLdh1j14F5mznnJyIBIhA8
    # oss访问地址:外网
    endpoint: oss-cn-shenzhen.aliyuncs.com
    # Bucket 名称
    bucketName: xijia-sz


## websocket 配置
websocket:
  # websocket 服务器部署地址的ip或者域名 --> 本地可以使用127.0.0.1 || localhost
  ip: 127.0.0.1
  # websocket 服务器端口,获取当前服务器端口
  port: ${server.port}
  # websocket 连接接口， WebsocketServiceImpl的 @ServerEndpoint 内参数
  interfaceName: /websocket


# DataSource Config
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure  # 为了某些版本的springboot  @SpringBootApplication(exclude= {DataSourceAutoConfiguration.class}) 无法生效
  datasource:
    dynamic:
      primary: db1 # 配置默认数据库
      datasource:
        db1: # 数据源1配置
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/spring-boot-plus2?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          type: com.alibaba.druid.pool.DruidDataSource
#        db2: # 数据源2配置
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://127.0.0.1:3306/spring-boot-plus2?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
#          username: root
#          password: 123456
#          type: com.alibaba.druid.pool.DruidDataSource


## 单数据源配置方法
# DataSource Config
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/spring-boot-plus2?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource