spring:
  # maven面板动态切换dev/pro环境
  profiles:
    active: @profiles.active@
  # 项目名
  application:
    name: xijia
  # 当遇到同样beng名字的时候，是否允许覆盖注册
  main:
    allow-bean-definition-overriding: true
  # 关闭thymeleaf缓存 开发时使用,否则没有实时画面
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  #时间格式处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  ## 文件上传配置
  servlet:
    multipart:
      max-file-size: 1024MB      # 单个文件的最大上限
      max-request-size: 1024MB   # 单个请求的文件总大小上限
  ## spring-boot-admin 配置
  boot:
    admin:
      ## admin 服务端访问地址
      context-path: /bootAdmin/
      ## admin 客户端连接服务端
      client:
        # 为了显示客户端的ip否则是以主机名显示的，这样需要添加hosts影射。
        instance:
          prefer-ip: true
        url: http://localhost:${server.port}/${spring.boot.admin.context-path}/
        #username: admin
        #password: admin@12345

  ## 数据源的连接的基础配置
  datasource:
    dynamic:
      druid:
        initialSize: 5    # 初始化大小
        minIdle: 5        # 最小值
        maxActive: 20     # 最大值
        maxWait: 60000    # 最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
        timeBetweenEvictionRunsMillis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接
        minEvictableIdleTimeMillis: 300000    # 配置一个连接在池中最小生存的时间
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
        # 'wall'用于防火墙，SpringBoot中没有log4j，我改成了 slf4j | log4j2
        filters: stat,wall,slf4j
        #最大PSCache连接
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    ## 监控平台配置
    druid:
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置StatViewServlet
      stat-view-servlet:
        # 访问地址
        url-pattern: "/druid/*"   # 访问地址 ip+端口/druid
        # allow: 127.0.0.1        # 允许那些ip, 不配置允许所有
        login-username: admin     # 账号
        login-password: 123456    # 密码
        deny: 192.168.1.102       # 禁止那些ip
        reset-enable: true        # 是否可以重置
        enabled: true             # 启用


# mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-enums-package: com.ws.ldy.enums.*
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# actuator 监控, 配置spring-boot-admin使用
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

