
server:
  port: 80   # HTTP (Tomcat) port
#  servlet:
#    context-path: /adminconsole   # 配置项目名 47.107.128.84
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xijia.plus:3306/spring-boot-plus2?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: root123456
    type: com.alibaba.druid.pool.DruidDataSource
