server:
  port: 8080   # HTTP (Tomcat) port
#  servlet:
#    context-path: /sheep   # 配置项目名47.107.128.84
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-boot-plus2?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: root123456
    type: com.alibaba.druid.pool.DruidDataSource
    #最大活跃数
    maxActive: 20s
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j

  main:
    allow-bean-definition-overriding: true #当遇到同样beng名字的时候，是否允许覆盖注册

  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update
    show-sql: true

  thymeleaf:    # 关闭thymeleaf缓存 开发时使用 否则没有实时画面
    cache: false
    check-template-location: true
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html

  jackson:  # 返回数据时间格式处理
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8