## 正式环境

## HTTP (Tomcat) port
server:
  port: 9049

# DataSource Config spring.datasource.dynamic.datasource.db1.url
spring:
  autoconfigure:
    # 为了某些版本的springboot  @SpringBootApplication(exclude= {DataSourceAutoConfiguration.class}) 无法生效
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: db1 # 配置默认数据库
      # | rewriteBatchedStatements=true mybatis批处理优化 | useTimezone=true&serverTimezone=GMT%2B8  使用北京时间 | useUnicode=true&characterEncoding=utf-8 编码 |
      datasource:
        db1: # 数据源1配置
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://xijia.plus/spring-boot-plus2?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
          username: root
          password: root123456
          type: com.alibaba.druid.pool.DruidDataSource



## 阿里云api
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com               # oss 接口访问地址:外网上传地址
    #endpoint: oss-cn-shenzhen-internal.aliyuncs.com     # oss 接口访问地址:内网上传地址
    accessKeyId: LTAI4Fyfy2DTf4yUrvKqHwH4                # 阿里云下oss 的 accessKeyId
    accessKeySecret: Jf3gn1kSRLdh1j14F5mznnJyIBIhA8      # 阿里云下oss 的 accessKeySecret
    bucketName: xijia-sz                                 # Bucket 名称
    # 访问域名(1-使用内网(配置服务器域名,使用nginx转发)  2-使用外网(直接配置,或nginx转发)  3-使用外网cdn(直接配置,或nginx转发))
    bucket: http://xijia-sz.oss-cn-shenzhen.aliyuncs.com
  sms:
    # 当前为乐陪配置
    accessKeyId: "LTAIDgBQsHDdlU8E"                      # 请在阿里云短信控制台获取
    accessKeySecret: "xZojnR8llxYzD0VJyNqfwWd5RsFKQk"    # 请在阿里云短信控制台获取
    signName: "阿里云短信测试专用"                          # 签名
    templateCode: "SMS_141915022"                        # 短信验证码模版(每个账号不一致,单独配置)

## 微信api
wx:
  # 小程序
  app:
    appId: "wxc3a142cbc777acc5"
    secret: "78077930fa44ba58c6b993da2c644505"
  # 公众号
  mq:
    appId: "wxa997b110821cbfd6"
    secret: "a5cee82a40995afc5bc14d17058908c1"
    token: "123456789"
    aesKey: "123456789"
  # 支付
  pay:
    appId: "wxc3a142cbc777acc5"
    mchId: "1512069221"
    mchKey: "v6fi8r2wegYnhOqve52tLzJrYk8L6GxS"
    subAppId: ""
    subMchId: ""
    keyPath: "classpath:cert/apiclient_cert.p12"
    # 回调地址
    notifyBase: "http://pets.api.520ban.com"
    orderNotifyUrl: "/api/pay/notify/wx/order"
    refundNotifyUrl: "/pay/notify/wx/refund"


## 七牛云
qiniu:
  oss:
    accessKey: "FetmKgfKFaS7ZAE12j5uzNSrXDkf6pp5LyAxtzWy"
    secretKey: "iY74NEU14YUA3lDUb1vy3Rt18pnEQvTgx37WxH2r"
    bucket: "xi-jia"
    hosts: "http://qiniu.file.xijia.plus/"
    priKey: ""
    ## 地域(华东 z0 华北 z1 华南 z2 北美 na0 东南亚 as0)
    area: "z2"


## 快递
kuaidu:
  # 快递100，授权码,客户码, 请到快递100页面申请企业版接口获取
  kuaidi100:
    key: vkvhbTZJ1059
    customer: 0953C663278B625ED2FB94AF1F3A02D6

  # 顺丰(丰桥) 个人账号沙盒测试地址(17628689969/ ws/19960302)
  sf:
    url: https://sfapi-sbox.sf-express.com/std/service    # 请求地址,沙盒, 正式地址=https://sfapi.sf-express.com/std/service
    customerCode: WSXX                                    # 请求地址
    customerCheckWord: sKfq2WO8V38rRFsyverQrnuuPfI0DS87   # 客户校检码
    customerMonthlyCard: 7551234567                       # 客户月结卡号（测试卡号）


## logback日志输出：linux 项目放置路径, 请自行配置log在服务器的输出路径，由 logback-spring.xml 读取此配置信息, 线上请配置linux路径: /usr/local/work/xijia2/logs
logging:
  # 日志目录, 线上请配置linux 绝对路径 如：/usr/local/work/xijia2/logs
  filePath: /usr/local/work/xijia2/logs
  # 配置日志路径即可实时输出到 spring-boot-admin 日志管理
  file: /usr/local/work/xijia2/log.txt
  # 需要记录到数据库的请求 (正式环境不建议记录GET 请求,太占资源)  支持：【GET,POST,PUT,DELETE】
  methods: POST,PUT,DELETE

