## 正式环境

server:
  port: 9049

spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  # 数据源配置
  datasource:
    dynamic:
      primary: db1
      datasource:
        db1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://xijia.plus/spring-boot-plus2?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
          username: root
          password: root123456
          type: com.alibaba.druid.pool.DruidDataSource
  # redis 配置
  redis:
    host: 47.108.201.177
    port: 6379
    password: 123456
    database: 15
    timeout: 1000s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-wait: -1
        max-active: -1

## 阿里云api
aliyun:
  ## 个人账号,拉取此代码调试后请修改为自己的,如发现滥用,将关停
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com   # oss-cn-shenzhen-internal.aliyuncs.com
    accessKeyId: LTAI4Fyfy2DTf4yUrvKqHwH4
    accessKeySecret: Jf3gn1kSRLdh1j14F5mznnJyIBIhA8
    bucketName: xijia-sz
    bucket: http://xijia-sz.oss-cn-shenzhen.aliyuncs.com

# 日志配置, filePath线上日志存放地址（logback-spring.xml 读取） , methods 记录那些请求数据到数据库
logging:
  filePath: /usr/local/work/xijia2/logs
  methods: POST,PUT,DELETE